package com.vn.logging;
// enums cho các log event xảy ra bên trong hệ thống
public enum LogEvent {
    HTTP_REQUEST_COMPLETED,
    JWT_AUTHENTICATION,

    REGISTER,
    VERIFY_EMAIL,
    LOGIN,
    REFRESH_TOKEN,
    RESEND_VERIFICATION_EMAIL,
    LOGOUT,

    SEND_VERIFICATION_EMAIL,

    GET_MY_PROFILE,
    UPDATE_MY_PROFILE,

    CREATE_BOOK,
    IMPORT_BOOKS,
    UPDATE_BOOK,
    DELETE_BOOK,
    UPDATE_BOOK_AUTHORS,
    CREATE_BOOK_COPY,
    UPDATE_BOOK_COPY,
    DELETE_BOOK_COPY,
    CREATE_AUTHOR,
    UPDATE_AUTHOR,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,

    BORROW_BOOK,
    RETURN_BOOK,
    RENEW_BORROW,
    CREATE_HOLD,
    CANCEL_HOLD,
    HOLD_READY_FOR_PICKUP,
    CHECKOUT_HOLD,
    AUTO_RENEWAL_JOB,
    AUTO_RENEWAL_ATTEMPT,
    SEND_AUTO_RENEWAL_EMAIL,
    MARK_OVERDUE_JOB,
    MARK_BORROW_OVERDUE,

    BUSINESS_EXCEPTION,
    VALIDATION_FAILED,
    ILLEGAL_ARGUMENT,
    ACCESS_DENIED,
    AUTHENTICATION_FAILED,
    MALFORMED_JSON,
    MISSING_REQUEST_PARAMETER,
    METHOD_NOT_ALLOWED,
    RESOURCE_NOT_FOUND,
    CONSTRAINT_VIOLATION,
    DATA_INTEGRITY_VIOLATION,
    UNHANDLED_EXCEPTION
}

