package com.vn.notification.enums;

public enum NotificationType {
    DUE_SOON_REMINDER,
    AUTO_RENEWAL_SUCCESS,
    AUTO_RENEWAL_FAILURE,
    BORROW_OVERDUE,
    HOLD_EXPIRED,
    HOLD_READY_FOR_PICKUP,
    MEMBERSHIP_EXPIRING,
    MEMBERSHIP_EXPIRED,
    ACCOUNT_BANNED,
    ACCOUNT_REACTIVATED
}
